[package]
name = "hello-actix-web"
version = "0.1.0"
authors = ["\"haoxin\" <\"haoxinst@gmail.com\">"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
bytes = "0.4"
cargo-expand = "0.4"
